---
packages:
        - htop
        - vim
        - sudo
users:
        - name: Ajout de plusieurs utilisateurs
          user: name={{ item.username }} shell=/bin/bash createhome=yes 
          password: name={{ item.password }}
          with_items: '{{users}}'

